### ISSUE TITLE
Cannot find the scatter_ts_interactive

### ISSUE THREAD

**Issue by RomainSohier** [Arf9999/rtweetXtras#3]
Hi again

I really like your package so I tried your update but it does not work for me.
When i ran this code : rtweetXtras::scatter_ts_interactive(mickey, title = "100 tweets about Mickey Mouse")
I get this issue -->Erreur : 'scatter_ts_interactive' is not an object exported from 'namespace:rtweetXtras'

When I ran this one : scatter_ts_interactive(mickey, title = "", print_immediately = TRUE), R does not find the function "scatter_ts_interactive"

Sorry about my warnings but I will show your package for my students and your beautiful data viz !

**Comment by Arf9999** [comment]
Ah.  I've had this issue before. Re-download and install from gitHub and then restart R.  That usually works.

Alternatively uninstall the package, and then re-install.  Usually restarting R is enough. 

I've also fixed an error, so the current version is 0.3.0.1000

**Comment by RomainSohier** [comment]
It works !

It's really really nice. Just a quick question : what is the code to make a small video (as you did on your tweet ?)

Bye and thanks !


[EM Normandie]<http://www.ecole-management-normandie.fr/>
Romain SOHIER
Docteur en Sciences de Gestion
Enseignant-chercheur en Marketing
Assistant Professor in Marketing

Tél.: +33 (0)2 32 92 58 40
[Accreditation EM Normandie]<https://www.ecole-management-normandie.fr/ecole/l-em-normandie/accreditations.html>


________________________________
De : Andrew Fraser <notifications@github.com>
Envoyé : lundi 7 décembre 2020 23:16
À : Arf9999/rtweetXtras <rtweetXtras@noreply.github.com>
Cc : SOHIER Romain <rsohier@em-normandie.fr>; Author <author@noreply.github.com>
Objet : Re: [Arf9999/rtweetXtras] Cannot find the scatter_ts_interactive (#3)


Ah. I've had this issue before. Re-download and install from gitHub and then restart R. That usually works.

Alternatively uninstall the package, and then re-install. Usually restarting R is enough.

I've also fixed an error, so the current version is 0.3.0.1000

**Comment by Arf9999** [comment]
I just used a screen capture to make the video.

Glad to hear it's working.

**Comment by RomainSohier** [comment]
Oh ok thanks !
Bye bye


[EM Normandie]<http://www.ecole-management-normandie.fr/>
Romain SOHIER
Docteur en Sciences de Gestion
Enseignant-chercheur en Marketing
Assistant Professor in Marketing

Tél.: +33 (0)2 32 92 58 40
[Accreditation EM Normandie]<https://www.ecole-management-normandie.fr/ecole/l-em-normandie/accreditations.html>


________________________________
De : Andrew Fraser <notifications@github.com>
Envoyé : mardi 8 décembre 2020 07:52
À : Arf9999/rtweetXtras <rtweetXtras@noreply.github.com>
Cc : SOHIER Romain <rsohier@em-normandie.fr>; Author <author@noreply.github.com>
Objet : Re: [Arf9999/rtweetXtras] Cannot find the scatter_ts_interactive (#3)


I just used a screen capture to make the video.

Glad to hear it's working.
